title: Liliia Verbenko 
logo: /assets/img/rsz_photo_1.png
description: LinkedIn http://www.linkedin.com/in/liliiaverbenko
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
